export const REGISTER_PEMATERI_REQUEST = "REGISTER_PEMATERI_REQUEST";
export const REGISTER_PEMATERI_SUCCESS = "REGISTER_PEMATERI_SUCCESS";
export const REGISTER_PEMATERI_ERROR = "REGISTER_PEMATERI_ERROR";